apiVersion: apps/v1
kind: ReplicaSet
metadata: # la metadata y los labels son informacion critica que debe ser diferente en cada aplicacion
  name: nginx-replicaset
  labels:
    app: nginx
spec:
  replicas: 3
  selector: # importante para que el replicaSet sepa que pods gestionar
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
